### ISSUE TITLE
Discord TagName?

### ISSUE THREAD

**Issue by T0biii** [KrisenKulturDE/gegen-das-virus.de_discordBot#3]
Wäre es nicht besser anstatt:
"Ein neuer Benutzer ist gejoint HausDude"
Den Discord Tag zu verwenden dann kann man wenigstens auch auf den Usernamen drücken.
Und 
"Ein neuer Benutzer ist gejoint @HausDude#7732" oder so ähnlich 

ich würde persönlich gejoint auch noch umbennen.

**Comment by NoobTenLuka** [comment]
Wir müssen gucken, ob wir den User in einem Channel, in welchem er nicht ist, markieren können.

**Comment by Fr13dr1ch** [comment]
@T0biii Coole Idee
